#!/usr/bin/env python3
"""
Raw UniPercept English Critique Extractor & Analyzer:
Parses all raw English outputs generated by UniPercept from benchmark logs & DB photos.
Analyzes vocabulary, sentence structure, strengths, missing elements, and score formatting.
"""

import os
import sys
import json
import re

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_ROOT = os.path.abspath(os.path.join(SCRIPT_DIR, ".."))

def analyze_raw_en_texts():
    raw_texts = []

    # 1. Load from benchmark_results_unipercept.json if exists
    bm_path = os.path.join(PROJECT_ROOT, "benchmark_results_unipercept.json")
    if os.path.exists(bm_path):
        with open(bm_path, "r", encoding="utf-8") as f:
            bm = json.load(f)
            for r_item in bm.get("rounds_data", []):
                for img_item in r_item.get("images", []):
                    f_name = img_item.get("file_name")
                    for p_name, p_res in img_item.get("prompt_results", {}).items():
                        critique = p_res.get("critique")
                        if critique:
                            raw_texts.append({
                                "source": "benchmark",
                                "file_name": f_name,
                                "prompt_name": p_name,
                                "critique": critique,
                                "quality_score": p_res.get("quality_score")
                            })

    print(f"[Analyzer] Total Raw EN UniPercept Critiques collected: {len(raw_texts)}")

    # Analysis metrics
    total = len(raw_texts)
    score_labels_count = 0
    exif_referenced_count = 0
    common_words = {}
    length_list = []
    has_structure_detail = 0

    for item in raw_texts:
        text = item["critique"]
        length_list.append(len(text))
        
        if "Score:" in text or "score:" in text:
            score_labels_count += 1
        if any(term in text.lower() for term in ["iso", "aperture", "f-stop", "shutter", "lens", "f/"]):
            exif_referenced_count += 1
        if any(term in text.lower() for term in ["texture", "resolution", "grain", "micro"]):
            has_structure_detail += 1

        # Tokenize words
        words = re.findall(r"\b[a-zA-Z]{3,}\b", text.lower())
        for w in words:
            common_words[w] = common_words.get(w, 0) + 1

    sorted_words = sorted(common_words.items(), key=lambda x: x[1], reverse=True)[:30]
    avg_len = sum(length_list) / len(length_list) if length_list else 0

    summary = {
        "total_critiques_analyzed": total,
        "avg_char_length": round(avg_len, 1),
        "score_label_presence_rate": f"{score_labels_count}/{total} ({(score_labels_count/total*100):.1f}%)" if total else "0%",
        "exif_reference_rate": f"{exif_referenced_count}/{total} ({(exif_referenced_count/total*100):.1f}%)" if total else "0%",
        "texture_detail_reference_rate": f"{has_structure_detail}/{total} ({(has_structure_detail/total*100):.1f}%)" if total else "0%",
        "top_frequent_vocabulary": sorted_words
    }

    out_file = os.path.join(PROJECT_ROOT, "scratch", "raw_unipercept_analysis_summary.json")
    os.makedirs(os.path.dirname(out_file), exist_ok=True)
    with open(out_file, "w", encoding="utf-8") as f:
        json.dump(summary, f, ensure_ascii=False, indent=2)

    print("\n==================================================")
    print(" 📊 UniPercept Raw English Critique Corpus Analysis")
    print("==================================================")
    print(f"- Total Raw EN Outputs Analyzed: {total}")
    print(f"- Average Character Length: {avg_len:.1f} chars")
    print(f"- Explicit Score Label Presence: {summary['score_label_presence_rate']}")
    print(f"- EXIF Metadata Direct Reference Rate: {summary['exif_reference_rate']}")
    print(f"- Texture & Micro-detail Reference Rate: {summary['texture_detail_reference_rate']}")
    print("\n[Top 15 Frequent Words]:")
    for w, cnt in sorted_words[:15]:
        print(f"  • {w}: {cnt} times")
    print("==================================================")

if __name__ == "__main__":
    analyze_raw_en_texts()
